### ISSUE TITLE
Project Outline:

### ISSUE THREAD

**Issue by jameslyleyoung** [timconseevable/liftoff-assignments#1]
Looks good.  

Only problem that I see is under Technology you have listed 4 things, all with a ? behind them.
I'm hoping for your MVP you will be building this app in C#, using Razor pages and other things you have learned while at LC, correct?  So, you can list all of those Technologies first, then, once you have the "How" you are going to build it, you can add the "What I want to learn to make it better" technologies.

To summarize, you will be building the app in C# like your final project from LC101, correct?'
So, list those in your Technologies Section.

And this isn't a hypothetical question.  I strongly/highly/imploringly suggest following along with the videos from Unit 3 CheeseMVCPersistant, and building out a similar Web Application.  The reasons I suggest this are many.  The first of which is that there are not a ton of jobs for Mobile dev in StL.  There are however available jobs for C# Web Dev.  So, build your project out in C#, and get a project under your belt, then improve it.  After you have it built out and you can show it to potential employers or what not, then go learn a new language/framework and build it back out.

**Comment by timconceivable** [comment]
Thanks for the advice!  I will make a working prototype in C# first then, and then look at making the mobile version.

**Comment by jameslyleyoung** [comment]
Looks good!
